apiVersion: v1
appVersion: "1.0.1"
description: A Helm chart for Callisto
name: callisto
version: 1.8.1-r1
sources:
- https://github.com/strufkin/callisto-chart
- https://github.com/wrike/callisto

maintainers:
- name: Wrike DevOps Team
  email: devops+oss@team.wrike.com
