apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "callisto.name" . }}-browser-pod-configmap
  labels:
    app: {{ template "callisto.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  browser-pod-configmap.yaml: |-
    {{ tpl ($.Files.Get "files/browser-pod-manifest.yaml") . | nindent 4 }}
