apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "callisto.name" . }}-nginx-configmap
  labels:
    app: {{ template "callisto.name" . }}-nginx
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  callisto-nginx.conf: |-
   {{ tpl ($.Files.Get "files/callisto-nginx.conf") . | nindent 4 }}
